#!/bin/bash
  
 cd
 rm -rf AUTORUN-CCMINER-SERVER
 git clone https://github.com/niyom007/AUTORUN-CCMINER-GITHUB
 cd ../etc/mobile-mining/set-miner
 cp -r online.json offline.json /../root/AUTORUN-CCMINER-GITHUB/mobile-mining/set-miner 
 cd
 cd ../etc
 rm -rf mobile-mining
 cd
 cd ../bin
 rm -rf add-ip edit-miner run-miner update up-grade
 cd
 cd AUTORUN-CCMINER-GITHUB
 chmod +x setupdate.sh
 sh setupdate.sh
