#!/bin/bash 
  
cd
rm -rf AUTORUN-CCMINER-SERVER
git clone https://github.com/niyom007/AUTORUN-CCMINER-SERVER
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-SERVER/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-ip edit-miner run-miner
cd
cd AUTORUN-CCMINER-SERVER 
chmod +x setupdate.sh
sh setupdate.sh
